#page title
page_title                                : Coala - Alert System                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://github.com/flozi00/coala/releases/download/0.1-alpha/app-debug.apk                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Coala                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The flexible alert system for assistance dogs and humans

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Florian Zimmermeister                                
your_link                                 :                      
your_city                                 : Germany                                
email_address                             : flozi00.fz@gmail.com
facebook_username                         :                                           
instagram_username                        : flozi00
twitter_username                          : 
github_username                           : flozi00
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Sustainable
    description                           : Old smartphones can in most cases be reused for the Coala system if the sensors still work.
    fontawesome_icon_name                 : tree
    
  - title                                 : flexible
    description                           : decide yourself what should happen when the alarm is triggered
    fontawesome_icon_name                 : clipboard-list

  - title                                 : Universal
    description                           : Use the system as you need it, without restrictions
    fontawesome_icon_name                 : play-circle

  - title                                 : mobile
    description                           : Use the system mobile, whereever you need with the pocket
    fontawesome_icon_name                 : sync

  - title                                 : stationary
    description                           : Use the as home emergency call with the stationary equipment
    fontawesome_icon_name                 : adjust
  
  - title                                 : many features
    description                           : Pick the alert features you need (Sound, SMS with coordinates, Call, API call)
    fontawesome_icon_name                 : star

  - title                                 : Trigger by anyone
    description                           : The sensors react on human touches and dog snouts, train your assistance dog for getting help
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Future triggers
    description                           : Looking forward to the audiotive and visual triggers for help cry's and unconscious person
    fontawesome_icon_name                 : link

  - title                                 : Saving lifes
    description                           : Alert this persons you want to, let Coala play instructions you want the first helpers should hear
    fontawesome_icon_name                 : info-circle




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#40B2B2"

link_color                                : "#FFA65C"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FFA65C"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
